### ISSUE TITLE
SolidusI18n error with solidus v2.0.0

### ISSUE THREAD

**Issue by useiichi** [solidusio-contrib/solidus_i18n#73]
I see forrowing error at Admin-Settings with solidus v2.0.0.
when I remove a line "gem 'solidus_i18n'" from Gemfile, I don't see this error.

```
NameError in Spree::Admin::GeneralSettings#edit

Showing /var/www/solidus/backend/app/views/spree/admin/general_settings/edit.html.erb where line #71 raised:

uninitialized constant SolidusI18n::LocaleHelper::Locale

Extracted source (around line #18):
16 # this project. solidusio/solidus now has those keys.
17 def all_locales_options
18 Locale.all.map { |locale| locale_presentation(locale) }.push(['English (EN)', :en])
19 end
20
21 private
```

**Comment by Takashi-U** [comment]
If you use Rails5, you should set autoloading is enable.

config/environments/production.rb
`config.enable_dependency_loading = true`

I also had the same problem, but was resolved with this.
As another method, you can also create a Locale class in the initializer. However, you need to set a reference destination locales folder.

I am not familiar with Rails, I do not know how may I send what kind of patch. Although the LocaleHelper in the app folder below is loaded, you will need to resolve the phenomenon in which the Locale is not loaded in the following lib folder.

**Comment by useiichi** [comment]
thanks. 
I'm using Rails5.
I'v resolved with your first method.

**Comment by useiichi** [comment]
It's better to solve this probrem without setting config.enable_dependency_loading = true.
I couldn't anderstand Takashi-U's second method.
Can anyone solve?

**Comment by tvdeyen** [comment]
@useiichi could you please try use the path from #78 in your app?

**Comment by useiichi** [comment]
thanks for tvdeyen.
but, I could'nt fix this probrem with your path from #78.
this error still occur.
